# Site settings
title: Jayvee Bustarde
description: Hi! Welcome to my personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jayvee Bustarde
user_description: I am a software developer especializing in Microsoft .Net technologies, currently on my 6th year of developing interesting projects. Right now, I am a part of Edenred, providing meal support products to various clients and their employees across Japan. I am a senior member of the team responsible for design, development, and deployment of various applications in our products system.
user_title: Software Developer
email: contact@jayveebustarde.com
linkedin_username: jayveebustarde
github_username:  jayveebustarde

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
